import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#c7c6c6",
        "tertiary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "tertiary-container": "#a6a5a5",
        "background": "#131313",
        "on-error-container": "#ffdad6",
        "tertiary": "#c8c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#ffdea5",
        "on-tertiary-fixed-variant": "#474747",
        "inverse-primary": "#775a19",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary": "#303030",
        "primary-fixed-dim": "#e9c176",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#5d4201",
        "error": "#ffb4ab",
        "surface-container": "#20201f",
        "on-surface-variant": "#d1c5b4",
        "on-primary-fixed": "#261900",
        "tertiary-fixed-dim": "#c8c6c6",
        "outline": "#9a8f80",
        "on-surface": "#e5e2e1",
        "secondary-container": "#464747",
        "primary": "#e9c176",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#b5b5b5",
        "on-primary-container": "#4e3700",
        "outline-variant": "#4e4639",
        "on-error": "#690005",
        "surface-bright": "#393939",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#3b3b3b",
        "on-secondary": "#2f3131",
        "on-primary": "#412d00",
        "surface-container-low": "#1c1b1b",
        "surface-dim": "#131313",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "secondary-fixed": "#e3e2e2",
        "surface-tint": "#e9c176",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#c5a059",
        "surface": "#131313"
      },
      fontFamily: {
        headline: ["var(--font-noto-serif)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
